# docker-compose.yml

version: '3.8'
services:

  postgres:
    image: postgres:latest
    container_name: battleship-db
    restart: always
    environment:
      - POSTGRES_DB=battleship_db
      - POSTGRES_USER=kantin
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres: